In [1]:
import pandas as pd

In [41]:
df=pd.read_excel(r"C:\Users\SKAN\Downloads\Customer Call List.xlsx")

In [42]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [11]:
df.shape

(21, 8)

In [4]:
df.dtypes

CustomerID            int64
First_Name           object
Last_Name            object
Phone_Number         object
Address              object
Paying Customer      object
Do_Not_Contact       object
Not_Useful_Column      bool
dtype: object

In [5]:
df.isnull().sum()

CustomerID           0
First_Name           0
Last_Name            1
Phone_Number         2
Address              0
Paying Customer      0
Do_Not_Contact       4
Not_Useful_Column    0
dtype: int64

In [6]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
dtype: bool

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df.shape

(20, 8)

In [16]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [18]:
df.drop(columns="Not_Useful_Column")

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [20]:
df.drop(columns="Not_Useful_Column")

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [43]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [46]:
df["Last_Name"]=df["Last_Name"].str.strip('123._/')

In [47]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [50]:
df["Phone_Number"]=df["Phone_Number"].str.replace('[^a-zA-Z0-9]','')

C:\Users\SKAN\AppData\Local\Temp\ipykernel_4044\2163535137.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df["Phone_Number"]=df["Phone_Number"].str.replace('[^a-zA-Z0-9]','')

In [51]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,False
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,Na,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True

In [72]:
df["Phone_Number"]=df["Phone_Number"].apply(lambda x:str(x))

In [84]:
df["Phone_Number"]=df["Phone_Number"].apply(lambda x: x[0:3] + '-'+x[3:6] +'-' + x[6:])

In [85]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,--,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,--,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,--,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,--,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [87]:
df[["Street Address","State","Zip_Code"]]=df["Address"].str.split(',',2,expand=True)

C:\Users\SKAN\AppData\Local\Temp\ipykernel_4044\2280620603.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df[["Street Address","State","Zip_Code"]]=df["Address"].str.split(',',2,expand=True)

In [88]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,White,--,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,--,1209 South Street,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,--,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,--,N/a,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None

In [91]:
df["Paying Customer"]=df["Paying Customer"].str.replace('Yes','Y')

In [92]:
df["Paying Customer"]=df["Paying Customer"].str.replace('No','N')

In [93]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Yes,False,93 West Main Street,None,None
2,1003,Walter,White,--,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,--,1209 South Street,N,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,--,123 Middle Earth,Y,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,No,True,612 Shire Lane,Shire,None
11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,--,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,--,N/a,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True,910 Tatooine Road,Tatooine,None

In [121]:
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace('Yes','Y')

In [124]:
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace('No','N')

In [125]:
df

,index,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,2,1003,Walter,White,--,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
2,4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
3,6,1007,Jeff,Winger,--,1209 South Street,N,N,1209 South Street,None,None
4,7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
5,8,1009,Gandalf,NaN,--,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
6,9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
7,10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
8,11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
9,12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
10,13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,None,None
11,14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
12,15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
13,16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
14,17,1018,Clark,Kent,--,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
15,19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None
16,20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [126]:
df.fillna('')

,index,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,2,1003,Walter,White,--,298 Drugs Driveway,N,,298 Drugs Driveway,,
2,4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
3,6,1007,Jeff,Winger,--,1209 South Street,N,N,1209 South Street,,
4,7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
5,8,1009,Gandalf,,--,123 Middle Earth,Y,,123 Middle Earth,,
6,9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
7,10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
8,11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
9,12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
10,13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
11,14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
12,15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
13,16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
14,17,1018,Clark,Kent,--,3498 Super Lane,Y,,3498 Super Lane,,
15,19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,
16,20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [128]:
df.drop(columns="Not_Useful_Column",inplace=True)

KeyError: "['Not_Useful_Column'] not found in axis"

In [129]:
df

,index,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,2,1003,Walter,White,--,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
2,4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
3,6,1007,Jeff,Winger,--,1209 South Street,N,N,1209 South Street,None,None
4,7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
5,8,1009,Gandalf,NaN,--,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
6,9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
7,10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
8,11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
9,12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
10,13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,None,None
11,14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
12,15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
13,16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
14,17,1018,Clark,Kent,--,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
15,19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None
16,20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [108]:
for x in df.index:
    if df.loc[x,"Do_Not_Contact"]=='Y':
        df.drop(x, inplace = True)

In [140]:
df

,index,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,2,1003,Walter,White,--,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
2,4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
3,6,1007,Jeff,Winger,--,1209 South Street,N,N,1209 South Street,None,None
4,7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
5,8,1009,Gandalf,NaN,--,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
6,9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
7,10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
8,11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
9,12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
10,13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,None,None
11,14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
12,15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
13,16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
14,17,1018,Clark,Kent,--,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
15,19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None
16,20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [164]:
for x in df.index:
    if df.loc[x,"Paying Customer"]== "N":
        df.drop(x, inplace = True)

In [165]:
df

,index,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
2,4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,8,1009,Gandalf,NaN,--,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
6,9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
7,10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
8,11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
9,12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
10,13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,None,None
13,16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
14,17,1018,Clark,Kent,--,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
15,19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None
16,20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [169]:
for x in df.index:
    if df.loc[x,"Do_Not_Contact"]== "":
        df.drop(x, inplace = True)

In [170]:
df

,index,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
2,4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,8,1009,Gandalf,NaN,--,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
6,9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
7,10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
8,11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
9,12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
10,13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,None,None
13,16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
14,17,1018,Clark,Kent,--,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
15,19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None
16,20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [171]:
df.dropna(subset="Phone_Number",inplace=True)

In [172]:
df

,index,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
2,4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,8,1009,Gandalf,NaN,--,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
6,9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
7,10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
8,11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
9,12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
10,13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,None,None
13,16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
14,17,1018,Clark,Kent,--,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
15,19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None
16,20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None